import groovy.json.*
args_map = [version:"1.$BUILD_NUMBER"]
print "Build number: "+BUILD_NUMBER
version = BUILD_NUMBER
print "version: "+version

pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        sh 'tar -zcvf public.tar.gz public'
      }
    }
    stage("OCI Upload Artifact") {
        steps {
          OCIUploadArtifact(credentialsId: 'kelowna-trails-global-credencials-apikey-fingerprint-tenantid-userid-regionid',
          uploadArtifactDetailsList: [[artifactPath: 'public.tar.gz',
          repositoryId: 'ocid1.artifactrepository.oc1.us-sanjose-1.0.amaaaaaaerm3fwyaoaagm6kks3fplpjcpfh3mapwcu2hltzs5mzhotdypbyq',
          repositoryType: 'GENERIC',
          sourcePath: 'public.tar.gz',
          version: "1.$BUILD_NUMBER"],
          [artifactPath: 'deployment_spec.yaml',
          repositoryId: 'ocid1.artifactrepository.oc1.us-sanjose-1.0.amaaaaaaerm3fwyaoaagm6kks3fplpjcpfh3mapwcu2hltzs5mzhotdypbyq',
          repositoryType: 'GENERIC',
          sourcePath: 'deployment_spec.yaml',
          version: "1.$BUILD_NUMBER"]
          ])
        }
    }
    stage('Trigger Deployment') {
        steps {
          OCIDeployment(argumentVal: JsonOutput.toJson(args_map),
          credentialsId: 'kelowna-trails-global-credencials-apikey-fingerprint-tenantid-userid-regionid',
          displayName: "testDeployment${BUILD_NUMBER}",
          endpoint: 'https://devops.us-sanjose-1.oci.oraclecloud.com',
          pipelineId: 'ocid1.devopsdeploypipeline.oc1.us-sanjose-1.amaaaaaaerm3fwyah7fudcr7gahhor665zfh577l3im6o54c4brxtj3pbf6a',
          pollingConfig: [timeoutSeconds: 600, "pollingIntervalSeconds" : 5], executionMode: 'SYNC'
          )
      }
    }  
  }
}
